version: '3.6'
services:
  kibanav6.2.4:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: kibanav6.2.4
    restart: always
    environment:
      - node.name=kibanav6.2.4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data.kibanav6.2.4
    ports:
      - 9600:9200
    networks:
      - net.kibanav6.2.4
      - externals

volumes:
  data.kibanav6.2.4:
    driver: local

networks:
  net.kibanav6.2.4:
    driver: bridge
  externals:
    external: true